<a href="https://colab.research.google.com/github/KarishmaSaxena/python-revise/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

      → Numerical Python
      → Used for fast mathematical and scientific computations
      → Performs vectorized operations (no explicit loops)
      → Stores homogeneous data types
      → Data stored in contiguous memory locations
      → Once an array is created, its size cannot be changed
      → Internally uses C / C++ / Fortran, so execution is faster than Python lists
      → Breaks tasks into fragments and processes them efficiently at a low level


In [ ]:
!pip install numpy
import numpy as np

List

      → Stores heterogeneous data types
      → Data stored in non-contiguous memory locations
      → Slower for large numerical computations
      → Size can grow or shrink dynamically

process_time()

      → Measures CPU execution time only
      → Ignores sleep / waiting time
      → Useful for benchmarking code performance

List vs NumPy (Time Taken)

      → List operations use Python loops → slower
      → NumPy uses vectorized operations → faster
      → NumPy executes operations in compiled C code
      → NumPy is more efficient for large datasets

In [15]:
#list
from time import process_time
lists= [i for i in range (1000000)]
start_time = process_time()
lists = [i+5 for i in lists] #cannot add a number directly
end_time = process_time()
print(end_time - start_time)

#numpy
import numpy as np
np_array = np.array([i for i in range (1000000)])
starting_time = process_time()
np_array += 5
ending_time = process_time()
print(ending_time - starting_time)

0.06019511299999891
0.001131132999997675


NumPy Arrays

      → Created using np.array() or np.asarray()
      → Can be 1-D, 2-D, or N-D
      → Shape defines dimensions of array
      → dtype defines data type of elements

Array Creation Functions

      → np.zeros(shape) → creates array filled with 0
      → np.ones(shape) → creates array filled with 1
      → np.full(shape, value) → creates array with same value
      → np.eye(rows, cols) → creates identity matrix
      → np.random.random(shape) → random float values (0–1)
      → np.random.randint(start, stop, shape) → random integers
      → np.linspace(start, stop, n) → evenly spaced values
      → np.arange(start, stop, step) → values with fixed step

List vs NumPy Array

      → List stores heterogeneous data
      → NumPy array stores homogeneous data
      → Lists use non-contiguous memory
      → NumPy arrays use contiguous memory
      → Lists are slower for mathematical operations
      → NumPy arrays are optimized and faster

List to NumPy Array

      → Nested lists with equal length → 2-D NumPy array
      → Unequal structure → object array (not recommended)
      → np.array() creates a new array
      → np.asarray() avoids copying if input is already an array

Key Advantage of NumPy

      → Faster computation
      → Less memory usage
      → Efficient large-scale data processing
      → Ideal for ML, Data Science, AI, Image Processing



In [68]:
#numpy array
np_array = np.array([1,2,3,4,5]) # elements has no commas
print(np_array)
print(type(np_array))
print(np_array.shape)
# 2-d array
np_array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(np_array2)
# 3d -arry
np_array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(np_array3)
print(np_array3.shape) # 3-d , 2 rows, 2 col
# data type
print(np_array.dtype)
np_array4 = np.array([1,2,3,4,5], dtype = float)
print(np_array4) # float data type
#list
list = [1,2,3,4,5]
print(list) # elements are separted by commas
print(type(list))
# created a numpy array of zeros
np_arrays= np.zeros((4,5))
print(np_arrays)
# created a numpy array of ones
np_arrys2=np.ones((4,4))
print(np_arrys2)
np_arr=np.full((2,3),6) # all arr  same value i.e 6-> 2 row , 2 col
print(np_arr)
# create an identity matrix
a=np.eye(3,4)
print(a)
# create value with random values
b = np.random.random((3,4))
print(b)
# create value random integer value with specfic range
c = np.random.randint(10,100,(4,5))
print(c)
#array with evenly space
np_arr5=np.linspace(100,200,(5)) # range 100-200 -> 5 elememts
print(np_arr5)
#array with evemly space with steps or gap
array1=np.arange(10,40,5) # here range 10-40 with diff of each 5 (start, stop, step)
print(array1)
#list to numpy array (also can use asrray)
list1=[[1,2,3,4,5],[6,7,8,9,10]]
print(np.array(list1))
print(type(np.array(list1)))

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
int64
[1. 2. 3. 4. 5.]
[1, 2, 3, 4, 5]
<class 'list'>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6]
 [6 6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0.07053825 0.72945343 0.50972921 0.3672331 ]
 [0.02825048 0.45480099 0.04856025 0.72549407]
 [0.12020567 0.87354416 0.31186655 0.88446014]]
[[69 81 55 88 97]
 [74 96 98 77 56]
 [99 53 22 35 85]
 [76 98 53 23 60]]
[100. 125. 150. 175. 200.]
[10 15 20 25 30 35]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


Analysis on numpy array

In [88]:
d = np.random.randint(100,400,(5,5))
print(d)
#dimension
print(d.shape)
#number of dimensions
print(d.ndim) # here row & col
# number of elements
print(d.size)
# check data type
print(d.dtype)
# accessing using index
print(d[0,0])
print(d[0,1])


[[108 106 240 172 215]
 [231 232 121 275 263]
 [339 340 387 323 357]
 [333 152 292 282 319]
 [140 233 315 129 170]]
(5, 5)
2
25
int64
108
106


Mathematical operations on numpy array


In [101]:
e=np.random.randint(100,200,(4,5))
print(e)
f=np.random.randint(200,300,(4,5))
print(f)
print("addition:",e+f)
print("subtract:",f-e)
print("multiple:",e*f)
print("modulos:", e%f)
print("divide:",e/f)
#add
print(np.add(4,5))
#subtract
print(np.subtract(12,6))

[[127 121 108 154 130]
 [148 116 127 102 195]
 [135 128 100 162 163]
 [198 191 121 124 176]]
[[281 294 237 282 264]
 [201 211 210 212 278]
 [266 261 274 297 297]
 [242 208 278 237 297]]
addition: [[408 415 345 436 394]
 [349 327 337 314 473]
 [401 389 374 459 460]
 [440 399 399 361 473]]
subtract: [[154 173 129 128 134]
 [ 53  95  83 110  83]
 [131 133 174 135 134]
 [ 44  17 157 113 121]]
multiple: [[35687 35574 25596 43428 34320]
 [29748 24476 26670 21624 54210]
 [35910 33408 27400 48114 48411]
 [47916 39728 33638 29388 52272]]
modulos: [[127 121 108 154 130]
 [148 116 127 102 195]
 [135 128 100 162 163]
 [198 191 121 124 176]]
divide: [[0.4519573  0.41156463 0.4556962  0.54609929 0.49242424]
 [0.73631841 0.54976303 0.6047619  0.48113208 0.70143885]
 [0.5075188  0.49042146 0.3649635  0.54545455 0.54882155]
 [0.81818182 0.91826923 0.4352518  0.52320675 0.59259259]]
9
6


Array Manuplication :

What Transpose Does

        → Converts rows into columns
        → Converts columns into rows
        → Shape changes from (m, n) to (n, m)
        → Data values remain the same, only position changes

Reshape:
        → Changes the shape of an array without changing its data


In [111]:
array_1=np.random.randint(100,200,(4,4))
array_2=np.random.randint(200,300,(4,4))
print(array_1)
print(array_2)
print(array_1.shape)
print(array_2.shape)
#Transpose
trans = np.transpose(array_1)
print(trans)
print(trans.shape)
# another menthod for tranpose -> T
TRAN= array_1.T
print(TRAN)
print(TRAN.shape)
# reshaping array
print(array_1.reshape(2,8))

[[109 115 165 168]
 [157 104 144 160]
 [185 197 161 143]
 [129 162 130 141]]
[[205 272 294 262]
 [235 288 274 272]
 [253 299 237 281]
 [259 250 257 264]]
(4, 4)
(4, 4)
[[109 157 185 129]
 [115 104 197 162]
 [165 144 161 130]
 [168 160 143 141]]
(4, 4)
[[109 157 185 129]
 [115 104 197 162]
 [165 144 161 130]
 [168 160 143 141]]
(4, 4)
[[109 115 165 168 157 104 144 160]
 [185 197 161 143 129 162 130 141]]
